version: '3.1'

services:

  mysqldb:
    image: mysql:9.0.1
    container_name: mysqldb
    restart: always
    env_file:
      - .env
    networks:
      - mysql-db-gui

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    env_file:
      - .env
    ports:
      - 8080:80
    networks:
      - mysql-db-gui
    depends_on:
      - mysqldb


networks:
  mysql-db-gui:
    driver: bridge